[workspace]
resolver = "2"

[package]
name = "zenflow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
thought-plugin = { git = "https://github.com/lexoliu/thought.git" }
askama = "0.12.1"
